drop trigger if exists trg_workflows_updated_at on public.workflows;
drop trigger if exists trg_organizations_updated_at on public.organizations;
drop function if exists public.set_updated_at();
drop function if exists public.workflow_avg_run_duration_seconds(public.workflows);
drop view if exists public.org_usage_view;
drop table if exists public.watched_table_events;
drop table if exists public.notification_events;
drop table if exists public.workflow_data;
drop table if exists public.step_runs;
drop table if exists public.workflow_runs;
drop table if exists public.workflow_triggers;
drop table if exists public.workflow_steps;
drop table if exists public.workflows;
drop table if exists public.org_members;
drop table if exists public.organizations;
